const db = require("./connection");
const { User, Product, Category } = require("../models");

db.once("open", async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { name: "Running" },
    { name: "Multi-Sport" },
    { name: "Health, Fitness" },
    { name: "Health" },
    { name: "Special Edition" },
    { name: "Smart Watch" },
    { name: "Fitness" },
    { name: "Kids, Fitness" },
    { name: "Fitness, Health" },
    { name: "Swimming" },
    { name: "Tactical" },
    { name: "Outdoors" },
    { name: "Surfing" },
    { name: "Golf" },
    { name: "Aviation" },
    { name: "Diving" },
    { name: "Rowing" },
    { name: "Racing" },
  ]);

  console.log("categories seeded");

  await Product.deleteMany();

  const products = await Product.insertMany([
    {
      name: "Forerunner® 945 LTE",
      picture:
        "https://static.garmincdn.com/en/products/010-02383-00/v/cf-lg-612cdd61-521d-4b93-abfb-58b6f55b5784.jpg",
      description:
        "You want to run without your phone and without worry. And you want a watch that takes training as seriously as you do. Dedicated runners and triathletes, this one is for you.",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2021/06/garmin-forerunner-945-lte-in-depthreviewhtml",
      releasedate: "6/2/2021",
      size: "44.4 x 44.4 x 13.9 mm\nFits wrists with a circumference of 128-218 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "49 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 945",
      picture:
        "https://static.garmincdn.com/en/products/010-02063-00/v/lf-lg-c953b888-3be5-4bfd-a636-0139efbac435.jpg",
      description: "Premium GPS running/triathlon smartwatch with music",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2019/04/garmin-forerunner-945-multisport-watch-in-depthreviewhtml",
      releasedate: "4/30/2019",
      size: "47 x 47 x 13.7 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "50 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 935",
      picture:
        "https://static.garmincdn.com/en/products/010-01746-00/v/pd-02-lg.jpg",
      description: "Premium GPS running/triathlon smartwatch with music",
      msrp: "500",
      review:
        "https://www.dcrainmaker.com/2017/03/garmin-forerunner-935-depthreviewhtml",
      releasedate: "3/29/2017",
      size: "47 x 47 x 13.9 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "49 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 745",
      picture:
        "https://static.garmincdn.com/en/products/010-02445-00/v/cf-lg-176dc461-6f42-455e-a71c-7d2e9ed90f59.jpg",
      description: "Advanced GPS 0and triathlon smartwatch",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2020/09/garmin-forerunner-745-depthreviewhtml",
      releasedate: "9/16/2020",
      size: "43.8 x 43.8 x 13.3 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "47 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 735XT",
      picture:
        "https://static.garmincdn.com/en/products/010-01614-01/v/cf-lg.jpg",
      description:
        "Advanced GPS 0watch with multisport features and wrist-based heart rate",
      msrp: "350",
      review:
        "https://www.dcrainmaker.com/2016/06/garmin-forerunner-735xt-in-depthreviewhtml",
      releasedate: "5/11/2016",
      size: "44.5 x 44.5 x 11.9 mm",
      displaysize: "1.23' (31.1 mm) diameter",
      displayresolution: "215 x 180 pixels",
      weight: "40.2 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 645 Music",
      picture:
        "https://static.garmincdn.com/en/products/010-01863-20/v/pd-01-lg-9ae7ab22-8b77-4edc-b67d-8cf053355629.jpg",
      description:
        "GPS 0smartwatch with Garmin Pay™ contactless payments, wrist-based heart rate and music",
      msrp: "450",
      review:
        "https://www.dcrainmaker.com/2018/03/garmin-forerunner-645-music-gps-watch-in-depthreviewhtml",
      releasedate: "1/9/2018",
      size: "42.5 x 42.5 x 13.5 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "42.2 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 645",
      picture:
        "https://static.garmincdn.com/en/products/010-01863-00/v/cf-lg-2ee668b0-3d19-4a6f-8ec8-1c1fdc8f5cf4.jpg",
      description:
        "GPS 0smartwatch with Garmin Pay™ contactless payments and wrist-based heart rate",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2018/03/garmin-forerunner-645-music-gps-watch-in-depthreviewhtml",
      releasedate: "1/9/2018",
      size: "42.5 x 42.5 x 13.5 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "41.8 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 245 Music",
      picture:
        "https://static.garmincdn.com/en/products/010-02120-21/v/cf-lg-24a31854-2918-4cda-ac8a-d17eaf4d95c7.jpg",
      description: "GPS 0smartwatch with advanced training features and music",
      msrp: "350",
      review:
        "https://www.dcrainmaker.com/2019/04/garmin-forerunner-245-music-gps-watch-in-depthreviewhtml",
      releasedate: "4/30/2019",
      size: "42.3 x 42.3 x 12.2 (mm)",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "38.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 245",
      picture:
        "https://static.garmincdn.com/en/products/010-02120-00/v/cf-lg-ecb01ad8-e7ce-4b80-97b0-cf8d1f3ece41.jpg",
      description: "GPS 0smartwatch with advanced training features",
      msrp: "300",
      review:
        "https://www.dcrainmaker.com/2019/04/garmin-forerunner-245-music-gps-watch-in-depthreviewhtml",
      releasedate: "4/30/2019",
      size: "42.3 x 42.3 x 12.2 (mm)",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "38.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 235",
      picture:
        "https://static.garmincdn.com/en/products/010-03717-54/v/cf-lg.jpg",
      description: "GPS 0watch with color display and wrist-based heart rate",
      msrp: "250",
      review:
        "https://www.dcrainmaker.com/2015/11/garmin-fr230-fr235reviewhtml",
      releasedate: "10/21/2015",
      size: "45 x 45 x 11.7 mm",
      displaysize: "1.23' (31.1 mm) diameter",
      displayresolution: "215 x 180 pixels",
      weight: "42 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 55",
      picture:
        "https://static.garmincdn.com/en/products/010-02562-01/v/cf-lg-26e853f6-2122-4df7-b72e-3c63be17c82e.jpg",
      description:
        "See yourself as a runner. Get the easy-to-use GPS 0smartwatch that encourages 0and healthy lifestyles.",
      msrp: "200",
      review:
        "https://www.dcrainmaker.com/2021/06/garmin-forerunner-55-depthreviewhtml",
      releasedate: "6/2/2021",
      size: "42 x 42 x 11.6 mm\nFits wrists with a circumference of 126-203 mm",
      displaysize: "1.04' (26.3 mm) diameter",
      displayresolution: "208 x 208 pixels",
      weight: "37 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 45",
      picture:
        "https://static.garmincdn.com/en/products/010-02156-06/v/lf-lg-e156ec57-3529-4090-8af9-68de9e357467.jpg",
      description: "GPS 0smartwatch with Garmin Coach training plan support",
      msrp: "200",
      review:
        "https://www.dcrainmaker.com/2019/04/garmin-forerunner-45-45s-gps-watch-in-depthreviewhtml",
      releasedate: "4/30/2019",
      size: "42 x 42 x 11.4 mm",
      displaysize: "1.04' (26.3 mm) diameter",
      displayresolution: "208 x 208 pixels",
      weight: "Small: 32 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 45S",
      picture:
        "https://static.garmincdn.com/en/products/010-02156-00/v/cf-lg-c0833bf0-4289-4e0b-81cc-e48f1e60b87c.jpg",
      description:
        "Smaller-sized GPS 0smartwatch with Garmin Coach training plan support",
      msrp: "200",
      review:
        "https://www.dcrainmaker.com/2019/04/garmin-forerunner-45-45s-gps-watch-in-depthreviewhtml",
      releasedate: "4/30/2019",
      size: "39.5 x 39.5 x 11.4 mm",
      displaysize: "1.04' (26.3 mm) diameter",
      displayresolution: "208 x 208 pixels",
      weight: "Small: 32 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[0]._id,
    },
    {
      name: "Forerunner® 35",
      picture:
        "https://static.garmincdn.com/en/products/010-01689-03/v/rf-lg.jpg",
      description: "Easy-to-use GPS 0watch with wrist-based heart rate",
      msrp: "170",
      review:
        "https://www.dcrainmaker.com/2016/09/hands-on-garmins-new-forerunner-35-with-optical-hr.html",
      releasedate: "8/31/2016",
      size: "35.5 x 40.7 x 13.3 mm",
      displaysize: "0.93' x 0.93' (23.5 x 23.4 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "37.3 g",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[0]._id,
    },
    {
      name: "Enduro™",
      picture:
        "https://static.garmincdn.com/en/products/010-02408-00/v/cf-lg-04000e87-146f-479c-a0d1-5fb2546242ff.jpg",
      description:
        "You’re an extreme endurance athlete, and you need a lighweightultraperformance GPS watch with epic battery life. This will help you go the distance.",
      msrp: "800",
      review:
        "https://www.dcrainmaker.com/2021/02/garmin-enduro-gps-watch-in-depthreviewhtml",
      releasedate: "2/16/2021",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Steel: 72 g (case only: 66 g)\nTitanium: 58 g (case only: 52 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6X – Pro Solar",
      picture:
        "https://static.garmincdn.com/en/products/010-02157-20/v/cf-lg-f8123592-8b9d-4db7-9563-75f287fb76a4.jpg",
      description:
        "Premium solar-powered multisport GPS watch with pace guidance, wrist-based heart rate, Pulse Ox, routable maps, music and more",
      msrp: "1000",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Titanium: 82 g (case only: 54 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6X - Pro/Sapphire",
      picture:
        "https://static.garmincdn.com/en/products/010-02157-10/v/cf-lg-e8dc39b5-158d-4aab-8ecf-eac6b9295eac.jpg",
      description:
        "Premium multisport GPS watches with wrist-based heart rate, Pulse Ox, pace guidance, routable maps, music and more",
      msrp: "750",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Steel: 93 g (case only: 66 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6 - Pro/Sapphire",
      picture:
        "https://static.garmincdn.com/en/products/010-02158-13/v/cf-lg-a836df96-628f-4aa8-8bc0-3d6ecaf0e1f4.jpg",
      description:
        "Premium multisport GPS watches with wrist-based heart rate, Pulse Ox, pace guidance, routable maps, music and more",
      msrp: "700",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "47 x 47 x 14.7 mm",
      displaysize: "1.3” (33.02 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "Steel: 83 g (case only: 60 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6S - Pro/Sapphire",
      picture:
        "https://static.garmincdn.com/en/products/010-02159-10/v/cf-lg-877bbbbd-9b15-41cd-9c8f-e212602518ee.jpg",
      description:
        "Smaller-sized multisport GPS watches with wrist-based heart rate, Pulse Ox, pace guidance, routable maps, music and more",
      msrp: "700",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "42 x 42 x 13.8 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "Steel: 61 g (case only: 44 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6",
      picture:
        "https://static.garmincdn.com/en/products/010-02158-00/g/cf-lg-a92acf0a-4c66-4e9e-8154-d7e1859bbde3.jpg",
      description:
        "Premium multisport GPS watch with wrist-based heart rate and Pulse Ox",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "47 x 47 x 14.7 mm",
      displaysize: "1.3” (33.02 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "Steel: 80 g (case only: 57 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 6S",
      picture:
        "https://static.garmincdn.com/en/products/010-02159-00/v/cf-lg-c79f00ad-c932-42ae-b89c-d3116a5539ff.jpg",
      description:
        "Smaller-sized multisport GPS watch with wrist-based heart rate and Pulse Ox",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-fenix6-pro-solar-seriesreviewhtml",
      releasedate: "",
      size: "42 x 42 x 13.8 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "Steel: 58 g (case only: 41 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5X Plus",
      picture:
        "https://static.garmincdn.com/en/products/010-01989-00/v/cf-lg-68bb7959-eb15-49a3-89c1-199ba5d1c2ef.jpg",
      description:
        "Ultimate multisport GPS smartwatch with wrist-based heart rate, Pulse Ox Acclimation, maps, music and Garmin Pay™ contactless payments",
      msrp: "750",
      review:
        "https://www.dcrainmaker.com/2018/06/garmin-fenix5-plus-5s-5x-in-depthreviewhtml",
      releasedate: "",
      size: "51 x 51 x 17.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "96 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5 Plus",
      picture:
        "https://static.garmincdn.com/en/products/010-01988-00/v/cf-lg-e37adc65-8f4c-47a1-b178-1a70a53c8416.jpg",
      description:
        "Premium multisport GPS smartwatch with wrist-based heart rate, maps, music and Garmin Pay™ contactless payments",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2018/06/garmin-fenix5-plus-5s-5x-in-depthreviewhtml",
      releasedate: "",
      size: "47 x 47 x 15.8 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "86 g\nTitanium version: 76 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5S Plus",
      picture:
        "https://static.garmincdn.com/en/products/010-01987-06/v/cf-lg-eaecd4ff-6927-4ba5-a4b1-5222b561f4ad.jpg",
      description:
        "Smaller-sized multisport GPS smartwatch with wrist-based heart rate, maps, music and Garmin Pay™ contactless payments",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2018/06/garmin-fenix5-plus-5s-5x-in-depthreviewhtml",
      releasedate: "",
      size: "42 x 42 x 15.4 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "65 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5X",
      picture:
        "https://static.garmincdn.com/en/products/010-01733-04/v/cf-lg.jpg",
      description:
        "Ultimate multisport watch with wrist-based heart rate and mapping",
      msrp: "600",
      review:
        "https://www.dcrainmaker.com/2017/03/garmin-fenix5-5s-5xreviewhtml",
      releasedate: "",
      size: "51 x 51 x 17.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "98 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5",
      picture:
        "https://static.garmincdn.com/en/products/010-01688-00/v/cf-lg.jpg",
      description: "Premium multisport GPS watch with wrist-based heart rate",
      msrp: "500",
      review:
        "https://www.dcrainmaker.com/2017/03/garmin-fenix5-5s-5xreviewhtml",
      releasedate: "",
      size: "47 x 47 x 15.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "85 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "fēnix® 5S",
      picture:
        "https://static.garmincdn.com/en/products/010-01685-00/v/cf-lg.jpg",
      description:
        "Smaller-sized multisport GPS watch with wrist-based heart rate",
      msrp: "500",
      review:
        "https://www.dcrainmaker.com/2017/03/garmin-fenix5-5s-5xreviewhtml",
      releasedate: "",
      size: "42 x 42 x 15 mm",
      displaysize: "1.1” (27.94 mm) diameter",
      displayresolution: "218 x 218 pixels",
      weight: "67 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[1]._id,
    },
    {
      name: "Venu® 2",
      picture:
        "https://static.garmincdn.com/en/products/010-02430-00/v/cf-lg-00170244-053b-4c3d-bde4-ee8ca6c6edd0.jpg",
      description:
        "To you, healthy living is about being more in touch with your mind and your body. Get the GPS smartwatch with advanced health and fitness features to help get you there.",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2021/04/garmin-venu2-venu2s-smartwatchreviewhtml",
      releasedate: "4/22/2021",
      size: "45.4 x 45.4 x 12.2 mm ",
      displaysize: "1.3' (33.0 mm) diameter",
      displayresolution: "416 x 416 pixels",
      weight: "49.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[2]._id,
    },
    {
      name: "Venu® 2S",
      picture:
        "https://static.garmincdn.com/en/products/010-02429-00/v/cf-lg-7c244e7b-031b-4b34-82ca-7ae951cfc580.jpg",
      description:
        "To you, healthy living is about being more in touch with your mind and your body. Get the smaller-sized GPS smartwatch with advanced health and fitness features to help get you there.",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2021/04/garmin-venu2-venu2s-smartwatchreviewhtml",
      releasedate: "4/22/2021",
      size: "40.4 x 40.4 x 12.1 mm",
      displaysize: "1.1” (27.9 mm) diameter",
      displayresolution: "360 x 360 pixels",
      weight: "38.2 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[2]._id,
    },
    {
      name: "Venu® Sq",
      picture:
        "https://static.garmincdn.com/en/products/010-02427-00/v/cf-lg-5c9c3397-9775-4ff7-a292-52c14b8730ea.jpg",
      description: "GPS smartwatch with all-day health monitoring",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2020/09/garmin-venu-sq-in-depthreviewhtml",
      releasedate: "9/23/2020",
      size: "40.6 x 37.0 x 11.5 mm",
      displaysize: "1.3' (33.1 mm) diagonal",
      displayresolution: "240 x 240 pixels",
      weight: "37.6 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "Venu® Sq – Music Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02426-00/v/cf-lg-8cf5f8e2-c3b7-4d7f-95eb-7c0b28d99f91.jpg",
      description: "GPS smartwatch with music and all-day health monitoring",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2020/09/garmin-venu-sq-in-depthreviewhtml",
      releasedate: "9/23/2020",
      size: "40.6 x 37.0 x 11.5 mm",
      displaysize: "1.3' (33.1 mm) diagonal",
      displayresolution: "240 x 240 pixels",
      weight: "37.6 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "Venu™",
      picture:
        "https://static.garmincdn.com/en/products/010-02173-11/v/cf-lg-de9b68c1-5cb9-4da3-85e0-1d627a90488d.jpg",
      description:
        "GPS smartwatch features AMOLED display, built-in sports apps, contactless payments, music and all-day health monitoring",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2019/09/garmin-venu-with-amoled-display-everything-you-ever-wanted-to-know.html",
      releasedate: "9/5/2019",
      size: "43.2 x 43.2 x 12.4 mm",
      displaysize: "1.2' (30.4mm) diameter",
      displayresolution: "390 x 390 pixels",
      weight: "46.3 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "First Avenger",
      picture:
        "https://static.garmincdn.com/en/products/010-02174-41/g/cf-lg-1488b8f7-7154-4eec-a549-9dbceaf6d9a7.jpg",
      description:
        "Special edition smartwatch with design and themed Garmin Connect™ experience inspired by Captain America\n© 2019 MARVEL",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "9/5/2019",
      size: "45.1 x 45.1 x 12.8 mm",
      displaysize: "1.3' (33.0 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "50.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[4]._id,
    },
    {
      name: "Darth Vader",
      picture:
        "https://static.garmincdn.com/en/products/010-02174-51/g/cf-lg-aed15f23-82b8-4afd-8e0b-213a22245803.jpg",
      description:
        "Special edition smartwatch with design and themed Garmin Connect™ experience inspired by your favorite character",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "",
      size: "45.1 x 45.1 x 12.8 mm",
      displaysize: "1.3' (33.0 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "50.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[4]._id,
    },
    {
      name: "Captain Marvel",
      picture:
        "https://static.garmincdn.com/en/products/010-02172-41/g/cf-lg-64967bdb-b02f-4c39-915b-6f9f97a7b6e5.jpg",
      description:
        "Special edition smartwatch with design and themed Garmin Connect™ experience inspired by Captain Marvel\n© 2019 MARVEL",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "9/5/2019",
      size: "40.0 x 40.0 x 12.7 mm",
      displaysize: "1.1' (27.9 mm) diameter",
      displayresolution: "218 x 218 pixels",
      weight: "40.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[4]._id,
    },
    {
      name: "Rey",
      picture:
        "https://static.garmincdn.com/en/products/010-02172-51/g/cf-lg-7082c68b-118a-4b4f-b4a8-dbd265b338ff.jpg",
      description:
        "Special edition smartwatch with design and themed Garmin Connect™ experience inspired by your favorite character",
      msrp: "400",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "",
      size: "40.0 x 40.0 x 12.7 mm",
      displaysize: "1.1' (27.9 mm) diameter",
      displayresolution: "218 x 218 pixels",
      weight: "40.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[4]._id,
    },
    {
      name: "vívoactive® 4",
      picture:
        "https://static.garmincdn.com/en/products/010-02174-01/v/cf-lg-a7a42f50-df93-4f76-b5a0-55dfa6f849ca.jpg",
      description:
        "GPS smartwatch features built-in sports apps, contactless payments, music and all-day health monitoring",
      msrp: "350",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "9/5/2019",
      size: "45.1 x 45.1 x 12.8 mm",
      displaysize: "1.3' (33.0 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "50.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "vívoactive® 4S",
      picture:
        "https://static.garmincdn.com/en/products/010-02172-31/v/lf-lg-9a9f73d8-1a82-43ef-91f8-64de881db6ce.jpg",
      description:
        "Smaller-sized GPS smartwatch features built-in sports apps, contactless payments, music and all-day health monitoring",
      msrp: "350",
      review:
        "https://www.dcrainmaker.com/2019/09/garmins-vivoactive-4-series-everything-you-need-to-know.html",
      releasedate: "9/5/2019",
      size: "40.0 x 40.0 x 12.7 mm",
      displaysize: "1.1' (27.9 mm) diameter",
      displayresolution: "218 x 218 pixels",
      weight: "40.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "vívoactive® 3 Music (Verizon)",
      picture:
        "https://static.garmincdn.com/en/products/010-01986-00/g/lf-lg-26f10301-dadb-4f73-9f8e-61a6d275b7fd.jpg",
      description:
        "Verizon connected GPS smartwatch with built-in sports apps, wrist-based heart rate, Garmin Pay™ contactless payments, music, and safety features",
      msrp: "300",
      review:
        "https://www.dcrainmaker.com/2018/06/garmin-vivoactive-3-music-everything-you-need-to-know.html",
      releasedate: "",
      size: "43.1 x 43.1 x 13.6 mm",
      displaysize: "1.2' (30.4mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "39.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "vivoactive 3 Music",
      picture:
        "https://static.garmincdn.com/en/products/010-01985-01/v/cf-lg-b939931b-2c86-4e07-85d7-74ce01d4a0f4.jpg",
      description:
        "GPS smartwatch with built-in sports apps, Garmin Pay™ contactless payments and wrist-based heart rate",
      msrp: "250",
      review:
        "https://www.dcrainmaker.com/2018/06/garmin-vivoactive-3-music-everything-you-need-to-know.html",
      releasedate: "7/13/2018",
      size: "43.1 x 43.1 x 13.6 mm",
      displaysize: "1.2' (30.4mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "39.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "vívoactive® 3",
      picture:
        "https://static.garmincdn.com/en/products/010-01769-01/v/cf-lg-f1ecd357-fab5-4120-87f1-52b7a5d7d1fc.jpg",
      description:
        "GPS smartwatch with built-in sports apps, Garmin Pay™ contactless payments and wrist-based heart rate",
      msrp: "250",
      review:
        "https://www.dcrainmaker.com/2017/10/garmin-vivoactive-3-in-depthreviewhtml",
      releasedate: "8/31/2017",
      size: "43.4 x 43.4 x 11.7 mm",
      displaysize: "1.2' (30.4mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "43.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[3]._id,
    },
    {
      name: "Lily™",
      picture:
        "https://static.garmincdn.com/en/products/010-02384-00/v/cf-lg-fc2a9acd-9fd6-4c66-8704-143c2cb1e183.jpg",
      description:
        "You’ve been waiting for a small, stylish smartwatch that’s classic enough for your jewelry box and modern enough to keep you connected. This one has an Italian leather band.",
      msrp: "200",
      review:
        "https://www.dcrainmaker.com/2021/01/garmin-lily-fitness-smartwatch.html",
      releasedate: "1/27/2021",
      size: "34.50 x 34.50 x 10.15 mm",
      displaysize: "1.00” x 0.84” (25.4 mm x 21.3 mm)",
      displayresolution: "240 x 201 pixels",
      weight: "24.0 g",
      waterrating: "5 ATM",
      colordisplay: "no (16 level grayscale)",
      category: categories[5]._id,
    },
    {
      name: "vívomove® Luxe",
      picture:
        "https://static.garmincdn.com/en/products/010-02241-02/v/cf-lg-4b61e80d-eb84-464f-89d7-c8534bad408f.jpg",
      description:
        "Elegant hybrid smartwatch with hidden dual color touchscreen display",
      msrp: "500",
      review: "",
      releasedate: "9/5/2019",
      size: "42 x 42 x 11.9 mm",
      displaysize: "0.95' x 0.74' (24.1 mm x 18.7 mm)",
      displayresolution: "240 x 240 pixels",
      weight:
        "Case only: 44.5 g\nWith leather strap: 55.5 g\nWith Milanese strap: 86.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[5]._id,
    },
    {
      name: "vívomove® Style",
      picture:
        "https://static.garmincdn.com/en/products/010-02241-00/v/cf-lg-55bb2c7d-f00a-4168-8557-dee61a049baa.jpg",
      description: "Hybrid smartwatch with dual color touchscreen display",
      msrp: "300",
      review: "",
      releasedate: "9/5/2019",
      size: "42 x 42 x 11.9 mm",
      displaysize: "0.95' x 0.74' (24.1 mm x 18.7 mm)",
      displayresolution: "240 x 240 pixels",
      weight:
        "Case only: 25.5 g\nWith silicone strap: 42.0 g\nWith nylon strap: 35.0 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[5]._id,
    },
    {
      name: "vívomove® 3S",
      picture:
        "https://static.garmincdn.com/en/products/010-02238-01/v/cf-lg-d4f2db8b-76a8-4ef1-b5cb-388f0da32dd0.jpg",
      description:
        "Smaller-sized hybrid smartwatch with hidden touchscreen display",
      msrp: "250",
      review: "",
      releasedate: "9/5/2019",
      size: "39 x 39 x 10.9 mm",
      displaysize: "0.35' x 0.72' (8.9 mm x 18.3 mm)",
      displayresolution: "64 x 132 pixels",
      weight: "Case only: 24.5 g\nWith silicone strap: 38.6 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "",
      category: categories[5]._id,
    },
    {
      name: "vívomove® 3",
      picture:
        "https://static.garmincdn.com/en/products/010-02239-00/v/cf-lg-11e27c39-8eaf-4731-9975-1225a94f5231.jpg",
      description: "Hybrid smartwatch with hidden touchscreen display",
      msrp: "250",
      review: "",
      releasedate: "9/5/2019",
      size: "44 x 44 x 11.3 mm",
      displaysize: "0.35' x 0.72' (8.9 mm x 18.3 mm)",
      displayresolution: "64 x 132 pixels",
      weight: "Case only: 29.6 g\nWith silicone strap: 46.1 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "",
      category: categories[5]._id,
    },
    {
      name: "vívomove® HR",
      picture:
        "https://static.garmincdn.com/en/products/010-01850-13/v/cf-lg-dfeba1c6-3452-4436-b300-ec2f4c5516bb.jpg",
      description: "Stylish hybrid smartwatch with activity tracking",
      msrp: "200",
      review:
        "https://www.dcrainmaker.com/2017/09/garmins-vivomove-hr-everything.html",
      releasedate: "",
      size: "43 x 43 x 11.6 mm",
      displaysize: "0.38' x 0.76' (9.6 mm x 19.2 mm)",
      displayresolution: "64 x 128 pixels",
      weight: "Sport: 40.8 g\nPremium: 56.5 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "",
      category: categories[5]._id,
    },
    {
      name: "Vivosport",
      picture:
        "https://static.garmincdn.com/en/products/010-01789-12/v/cf-lg.jpg",
      description:
        "Smart fitness tracker with wrist-based heart rate, GPS and color display",
      msrp: "170",
      review: "https://www.dcrainmaker.com/2017/09/garmin-vivosportreviewhtml",
      releasedate: "",
      size: "Width: 21.0 mm",
      displaysize: "0.38' x 0.76' (9.7 mm x 19.3 mm)",
      displayresolution: "72 x 144 pixels",
      weight: "Small/medium: 24.1 g",
      waterrating: "Swim",
      colordisplay: "Yes",
      category: categories[6]._id,
    },
    {
      name: "Vivosmart 4",
      picture:
        "https://static.garmincdn.com/en/products/010-01995-13/v/cf-lg-a7c10e25-650d-4104-b352-7eaca240c0ae.jpg",
      description:
        "Slim, smart fitness tracker with a wrist-based Pulse Ox sensor and energy monitoring",
      msrp: "130",
      review: "",
      releasedate: "",
      size: "Small/medium: 15 x 10.5 x 197 mm",
      displaysize: "0.26' x 0.70' (6.6 mm x 17.7 mm)",
      displayresolution: "48 x 128 pixels",
      weight: "Small/medium: 16.5 g",
      waterrating: "Swim",
      colordisplay: "",
      category: categories[6]._id,
    },
    {
      name: "vívofit® 4",
      picture:
        "https://static.garmincdn.com/en/products/010-01847-03/v/cf-lg-aa7c74ec-4547-4121-8db3-2368aeb5371d.jpg",
      description:
        "Fitness tracker with always-on color display and 1+ year battery life",
      msrp: "80",
      review: "",
      releasedate: "",
      size: "Width: 19 mm",
      displaysize: "0.43' x 0.43' (11 x 11 mm)",
      displayresolution: "88 x 88 pixels",
      weight: "Small/medium: 25 g\nLarge: 25.5 g",
      waterrating: "Swim",
      colordisplay: "",
      category: categories[6]._id,
    },
    {
      name: "vívofit® jr. 3",
      picture:
        "https://static.garmincdn.com/en/products/010-02441-30/v/cf-lg-152d6fbf-3dba-4115-af13-358f3ec81efc.jpg",
      description:
        "You want a next-level fitness tracker for your kid. With a parent-controlled app for you, plus Marvel Studios’ Infinity Saga app adventures and games your child can unlock by staying active.\n© 2020 MARVEL",
      msrp: "80",
      review: "",
      releasedate: "",
      size: "Adjustable band fits 130-175 mm (ages 4+).",
      displaysize: "0.56' x 0.56' (14.11 x 14.11 mm)",
      displayresolution: "112 x 112 pixels",
      weight: "25 g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[7]._id,
    },
    {
      name: "vívofit® jr. 2",
      picture:
        "https://static.garmincdn.com/en/products/010-01909-13/g/cf-lg-03c57ea8-ec4f-490a-8eda-03827356c6d3.jpg",
      description:
        "First Order™ fitness tracker for kids with themed app adventures\n© & ™ Lucasfilm Ltd.",
      msrp: "70",
      review:
        "https://www.dcrainmaker.com/2017/09/garmin-vivofit-jr-2revieweverything-you-ever-wanted-to-know.html",
      releasedate: "",
      size: "Stretchy bands accommodate wrists up to 147 mm (ages 4-7)",
      displaysize: "0.43' x 0.43' (11 x 11 mm)",
      displayresolution: "88 x 88 pixels",
      weight: "17.5 g",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[7]._id,
    },
    {
      name: "vívofit® jr.",
      picture:
        "https://static.garmincdn.com/en/products/010-01634-00/v/cf-lg.jpg",
      description: "Kid’s fitness tracker with free parent mobile app",
      msrp: "70",
      review: "",
      releasedate: "",
      size: "Regular accommodates wrists up to 145 mm",
      displaysize: "0.39' x 0.39' (10 mm x 10 mm)",
      displayresolution: "64 x 64 pixels",
      weight: "17.5 g",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[7]._id,
    },
    {
      name: "Garmin Swim™ 2",
      picture:
        "https://static.garmincdn.com/en/products/010-02247-01/v/cf-lg-ab75ebee-c3ed-4229-b81f-a690120d578f.jpg",
      description: "GPS swimming smartwatch for the pool and open water",
      msrp: "250",
      review:
        "https://www.dcrainmaker.com/2019/10/garmin-swim-2-openwater-pool-gps-watchreviewhtml",
      releasedate: "",
      size: "42 x 42 x 11.4 mm",
      displaysize: "1.04' (26.3 mm) diameter",
      displayresolution: "208 x 208 pixels",
      weight: "36 g",
      waterrating: "Swim, 5 ATM",
      colordisplay: "Yes",
      category: categories[8]._id,
    },
    {
      name: "tactix® Delta - Solar Edition with Ballistics",
      picture:
        "https://static.garmincdn.com/en/products/010-02357-50/v/cf-lg-6a8b18fd-6977-4cb8-b54f-953460997ce0.jpg",
      description:
        "Specialized solar powered GPS smartwatch with tactical features and Applied Ballistics",
      msrp: "1120",
      review: "",
      releasedate: "",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Steel: 97 g (case only: 69 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[9]._id,
    },
    {
      name: "tactix® Delta - Solar Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02357-10/v/cf-lg-03189da7-4d7c-4293-ac82-527e2882daa2.jpg",
      description:
        "Specialized solar powered GPS smartwatch with tactical features",
      msrp: "880",
      review: "",
      releasedate: "",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Steel: 97 g (case only: 69 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[9]._id,
    },
    {
      name: "tactix® Delta Sapphire",
      picture:
        "https://static.garmincdn.com/en/products/010-02357-00/g/cf-lg-2c2fad14-11ab-4115-90bf-22cd64eae0d4.jpg",
      description:
        "Specialized GPS smartwatch with tactical features, Pulse Ox, pace guidance, routable TOPO mapping and more",
      msrp: "900",
      review: "",
      releasedate: "1/20/2020",
      size: "51 x 51 x 14.9 mm\n",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "Steel: 97 g (case only: 69 g)",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[9]._id,
    },
    {
      name: "tactix® Charlie",
      picture:
        "https://static.garmincdn.com/en/products/010-02084-00/g/cf-lg-b6cc2880-6b9b-4d69-ac31-a7e26a12afd9.jpg",
      description:
        "Multifunction GPS watch with routable TOPO mapping, wrist-based heart rate and tactical features",
      msrp: "750",
      review: "",
      releasedate: "",
      size: "51 x 51 x 17.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "90 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[9]._id,
    },
    {
      name: "Instinct® Solar – Tactical Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02293-13/v/cf-lg-c8b74ddb-47f2-4ec6-8550-9b237aef02b0.jpg",
      description:
        "Rugged GPS smartwatch with solar charging and tactical features",
      msrp: "360",
      review:
        "https://www.dcrainmaker.com/2020/07/garmin-instinct-solarreviewwhats-new-different.html",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "53 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[9]._id,
    },
    {
      name: "Instinct® Solar",
      picture:
        "https://static.garmincdn.com/en/products/010-02293-10/v/cf-lg-b31fcc72-a9a9-466b-9231-8e57a732e677.jpg",
      description: "Rugged GPS smartwatch with solar charging",
      msrp: "360",
      review:
        "https://www.dcrainmaker.com/2020/07/garmin-instinct-solarreviewwhats-new-different.html",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "53 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[10]._id,
    },
    {
      name: "Instinct® Solar – Surf Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02293-17/v/cf-lg-96e7e174-004c-4ceb-a162-24a82121784f.jpg",
      description:
        "Rugged GPS smartwatch with solar charging and dedicated surf features",
      msrp: "360",
      review:
        "https://www.dcrainmaker.com/2020/07/garmin-instinct-solarreviewwhats-new-different.html",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "53 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[11]._id,
    },
    {
      name: "Instinct® – Tactical Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02064-70/v/cf-lg-9c1a3be9-7c41-4009-9f84-d32bad3f31b6.jpg",
      description: "Rugged, reliable outdoor GPS watch with tactical features",
      msrp: "350",
      review:
        "https://www.dcrainmaker.com/2018/10/garmin-instinct-gps-watch-in-depthreviewhtml",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "52 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[9]._id,
    },
    {
      name: "Instinct® - Esports Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02064-72/g/cf-lg-2be98ce2-6828-41c5-9a9b-7d54709eaaf1.jpg",
      description: "Rugged, GPS smartwatch with Esport activity profile",
      msrp: "300",
      review:
        "https://www.dcrainmaker.com/2020/10/garmin-instinct-esports-edition-all-the-details.html",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "52 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[4]._id,
    },
    {
      name: "Instinct®",
      picture:
        "https://static.garmincdn.com/en/products/010-02064-00/v/cf-lg-18a7a0af-8bbf-4bba-9468-e4969090e9ca.jpg",
      description: "Rugged, reliable outdoor GPS watch",
      msrp: "300",
      review:
        "https://www.dcrainmaker.com/2018/10/garmin-instinct-gps-watch-in-depthreviewhtml",
      releasedate: "",
      size: "45 x 45 x 15.3 mm",
      displaysize: "custom, two-window design; 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "52 g",
      waterrating: "10 ATM",
      colordisplay: "",
      category: categories[10]._id,
    },
    {
      name: "Approach® S62",
      picture:
        "https://static.garmincdn.com/en/products/010-02200-00/v/cf-lg-19b33cf3-f705-44da-8ea8-2139048fb066.jpg",
      description:
        "Premium GPS golf watch with Virtual Caddie and other advanced features",
      msrp: "400",
      review: "",
      releasedate: "",
      size: "47 x 47 x 14.8 mm",
      displaysize: "1.3” (33.02 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "2.2 oz (61 g)",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "Approach® S60",
      picture:
        "https://static.garmincdn.com/en/products/010-01702-03/v/pd-02-lg.jpg",
      description:
        "Premium GPS golf watch with color touchscreen and the most sophisticated training/playing features",
      msrp: "400",
      review: "",
      releasedate: "",
      size: "46 x 46 x 14.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "standard: 1.8 oz (52 g)",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "Approach® G12",
      picture:
        "https://static.garmincdn.com/en/products/010-02555-00/v/cf-lg-5066094a-d144-4e2d-adcf-05d431636729.jpg",
      description:
        "You’re a golfer, but you don’t want a watch slowing down your swing. You need a simple golf range finder you can clip to your pocket or golf bag.",
      msrp: "150",
      review: "",
      releasedate: "3/16/2021",
      size: "",
      displaysize: "0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "175 x 175 pixels",
      weight: "0.9 oz (25.1 g)",
      waterrating: "IPX7",
      colordisplay: "",
      category: categories[12]._id,
    },
    {
      name: "Approach® S42",
      picture:
        "https://static.garmincdn.com/en/products/010-02572-10/v/cf-lg-5ed90c18-d9f4-4994-af6d-7dce137f35b7.jpg",
      description:
        "You’re looking for a smartwatch that helps you tee off with confidence. Something that can be worn on and off the course. Here it is.",
      msrp: "300",
      review: "",
      releasedate: "3/16/2021",
      size: "43.4 x 43.4 x 11.7 mm\nSmall/Medium version fits wrists with a circumference of 106-176 mm (Silver/White and Rose Gold/Light Sand versions)\nOne Size versions fit wrists with a circumference of 125-202 mm (Black/Gunmetal only)",
      displaysize: "1.2 in (30.4mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "1.5 oz (43 g)",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "Approach® S40",
      picture:
        "https://static.garmincdn.com/en/products/010-02140-02/v/cf-lg-db2d6026-1289-438c-9eb2-32add07f8ec7.jpg",
      description: "Stylish GPS golf smartwatch with color touchscreen",
      msrp: "300",
      review: "",
      releasedate: "",
      size: "43.4 x 43.4 x 11.7 mm",
      displaysize: "1.2 in (30.4mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "1.5 oz (43 g)",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "Approach® S20",
      picture:
        "https://static.garmincdn.com/en/products/010-03723-01/v/sc-02-lg.jpg",
      description: "GPS golf watch with automatic club tracking system",
      msrp: "200",
      review: "",
      releasedate: "",
      size: "37.4 x 47.6 x 11.3 mm",
      displaysize: " 0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "1.5 oz (42.2 g)",
      waterrating: " 5 ATM",
      colordisplay: "",
      category: categories[12]._id,
    },
    {
      name: "Approach® S12",
      picture:
        "https://static.garmincdn.com/en/products/010-02472-00/v/cf-lg-b3827053-718e-41bf-8d07-124cffacad41.jpg",
      description:
        "You want a smartwatch that’s made specifically for golf. One that keeps it simple and helps lower your score. Look no further.",
      msrp: "200",
      review: "",
      releasedate: "3/16/2021",
      size: "43.7 x 43.7 x 11.5 mm\nFits wrists with a circumference of 125-202 mm",
      displaysize: "0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "175 x 175 pixels",
      weight: "1.20 oz (34.1 g)",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[12]._id,
    },
    {
      name: "Approach® S10",
      picture:
        "https://static.garmincdn.com/en/products/010-02028-02/v/cf-lg-e3b5e8d8-0989-48e7-9a98-7212c374bbc1.jpg",
      description: "GPS golf watch",
      msrp: "150",
      review: "",
      releasedate: "",
      size: "35.5 x 40.7 x 11.3 mm",
      displaysize: "0.9” x 0.9” (23 x 23 mm)",
      displayresolution: "128 x 128 pixels",
      weight: "1.2 oz (35.0 g)",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[12]._id,
    },
    {
      name: "Approach X40",
      picture:
        "https://static.garmincdn.com/en/products/010-01513-01/v/cf-lg.jpg",
      description:
        "GPS golf band with wrist-based heart rate and activity tracking",
      msrp: "250",
      review: "",
      releasedate: "",
      size: "Width: 0.83” (21.1 mm)",
      displaysize: "1.00” x 0.42” (25.4 x 10.7 mm)",
      displayresolution: "160 x 68 pixels",
      weight: "1.1 oz (31 g)",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "Approach® X10",
      picture:
        "https://static.garmincdn.com/en/products/010-01851-00/v/cf-lg.jpg",
      description: "GPS golf band",
      msrp: "170",
      review: "",
      releasedate: "",
      size: "Width: 0.85” (21.5 mm)",
      displaysize: "1.00 x 0.42' (25.4 x 10.7mm)",
      displayresolution: "160 x 68 pixels",
      weight: "1.1 oz (31 g)",
      waterrating: "5 ATM",
      colordisplay: "",
      category: categories[12]._id,
    },
    {
      name: "D2™ Delta PX",
      picture:
        "https://static.garmincdn.com/en/products/010-01989-30/g/cf-lg-e7230fb9-1d53-45a2-b7c7-f5c31984bfed.jpg",
      description:
        "Premium GPS aviator watch with color moving map, NEXRAD weather, Pulse Ox, wrist heart rate, smart notifications, logbook, music and Garmin Pay™ contactless payments",
      msrp: "1250",
      review: "",
      releasedate: "",
      size: "51 x 51 x 17.5 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "87 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
    {
      name: "D2™ Delta",
      picture:
        "https://static.garmincdn.com/en/products/010-01988-30/g/pd-02-lg-612e9a56-85b3-4593-a852-bc0e496f8718.jpg",
      description:
        "Premium GPS aviator watch with color mapping, NEXRAD weather, wrist heart rate, smart notifications, logbook, music and Garmin Pay™ contactless payments",
      msrp: "950",
      review: "",
      releasedate: "",
      size: "47 x 47 x 15.8 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "76 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
    {
      name: "D2™ Delta S",
      picture:
        "https://static.garmincdn.com/en/products/010-01987-30/g/cf-lg-de4d6881-1d09-4ff8-9dcf-e3a90418752a.jpg",
      description:
        "Smaller-sized GPS aviator watch with color moving map, NEXRAD weather, wrist heart rate, smart notifications, logbook, music and Garmin Pay™ contactless payments",
      msrp: "900",
      review: "",
      releasedate: "",
      size: "42 x 42 x 15.4 mm",
      displaysize: "1.2' (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "65 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
    {
      name: "D2™ Air",
      picture:
        "https://static.garmincdn.com/en/products/010-02173-41/g/cf-lg-fb4833b5-650e-4c32-addb-65e0a52b5e35.jpg",
      description: "GPS smartwatch for aviators",
      msrp: "500",
      review: "",
      releasedate: "",
      size: "43.2 x 43.2 x 12.4 mm",
      displaysize: "1.2' (30.4mm) diameter",
      displayresolution: "390 x 390 pixels",
      weight: "46.3g",
      waterrating: "5 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
    {
      name: "Descent™ Mk1",
      picture:
        "https://static.garmincdn.com/en/products/010-01760-00/v/cf-lg.jpg",
      description:
        "Watch-style dive computer with surface GPS navigation, color TOPO mapping and multisport features",
      msrp: "1000",
      review:
        "https://www.dcrainmaker.com/2017/10/garmins-descent-mk1-diving-gps.html",
      releasedate: "",
      size: "51 x 51 x 17.8 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight:
        "steel with silicone band: 101 g\ntitanium with silicone band: 94 g\ntitanium with titanium band: 145 g",
      waterrating: "Dive (Designed to comply with EN13319)",
      colordisplay: "Yes",
      category: categories[14]._id,
    },
    {
      name: "Descent™ Mk2",
      picture:
        "https://static.garmincdn.com/en/products/010-02132-00/v/cf-lg-90f9236a-78f2-4f4f-b461-d7d89eba9b42.jpg",
      description:
        "Watch-style dive computer with surface GPS navigation, Pulse Ox, multisport features and more",
      msrp: "1300",
      review: "",
      releasedate: "",
      size: "",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "silicone band: 103.8 g",
      waterrating: "Dive (100 meters)",
      colordisplay: "Yes",
      category: categories[14]._id,
    },
    {
      name: "Descent™ Mk2i",
      picture:
        "https://static.garmincdn.com/en/products/010-02132-01/v/cf-lg-9fe513c6-ff71-4e1a-a15c-61545696a57b.jpg",
      description:
        "Watch-style dive computer with air integration, surface GPS navigation, Pulse Ox, multisport features and more",
      msrp: "1500",
      review: "",
      releasedate: "",
      size: "",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "silicone band: 99.6 g\ntitanium band: 160.3 g",
      waterrating: "Dive (100 meters)",
      colordisplay: "Yes",
      category: categories[14]._id,
    },
    {
      name: "Descent™ Mk2S",
      picture:
        "https://static.garmincdn.com/en/products/010-02403-00/v/cf-lg-348eba9e-d082-49bd-840c-e71bbbb3ca05.jpg",
      description:
        "Smaller watch-sized dive computer with surface GPS navigation, color TOPO mapping and multisport features",
      msrp: "1000",
      review: "",
      releasedate: "",
      size: "",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "silicone band: 60 g\ncase only: 41 g",
      waterrating: "Dive (100 meters)",
      colordisplay: "Yes",
      category: categories[14]._id,
    },
    {
      name: "quatix® 6X Solar",
      picture:
        "https://static.garmincdn.com/en/products/010-02157-30/g/cf-lg-51ceb9e7-a658-4506-8b3a-a8eea58fed3d.jpg",
      description: "Ultimate solar powered marine and outdoor smartwatch",
      msrp: "1150",
      review: "",
      releasedate: "",
      size: "51 x 51 x 14.9 mm",
      displaysize: "1.4” (35.56 mm) diameter",
      displayresolution: "280 x 280 pixels",
      weight: "82 g (54 g, case only)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[15]._id,
    },
    {
      name: "quatix® 6",
      picture:
        "https://static.garmincdn.com/en/products/010-02158-90/g/cf-lg-75ccd32f-c34f-408f-90db-06472aed9598.jpg",
      description:
        "Premium multisport GPS watches with wrist-based heart rate, Pulse Ox, pace guidance, routable maps, music and more",
      msrp: "700",
      review: "",
      releasedate: "4/2/2020",
      size: "47 x 47 x 14.7 mm",
      displaysize: "1.3” (33.02 mm) diameter",
      displayresolution: "260 x 260 pixels",
      weight: "Steel: 83 g (case only: 60 g)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[15]._id,
    },
    {
      name: "quatix® 5 Sapphire",
      picture:
        "https://static.garmincdn.com/en/products/010-01688-41/g/cf-lg.jpg",
      description:
        "Premium multisport marine smartwatch that provides comprehensive boat connectivity, featuring a sapphire lens and Wi-Fi® connectivity",
      msrp: "800",
      review: "",
      releasedate: "",
      size: "47 x 47 x 15.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "Silicone band: 85 g\nMetal band: 156 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[15]._id,
    },
    {
      name: "quatix® 5",
      picture:
        "https://static.garmincdn.com/en/products/010-01688-40/g/cf-lg.jpg",
      description:
        "Premium multisport marine smartwatch that provides comprehensive boat connectivity",
      msrp: "550",
      review: "",
      releasedate: "",
      size: "47 x 47 x 15.5 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "silicone band: 85 g\nmetal band: 156 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[15]._id,
    },
    {
      name: "MARQ® Driver",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-00/g/cf-lg-7085593e-3acb-485d-8ce4-61297b9c9458.jpg",
      description: "Modern tool watch with tachymeter and preloaded racetracks",
      msrp: "2500",
      review: "",
      releasedate: "3/13/2019",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "128 g (95 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[16]._id,
    },
    {
      name: "MARQ® Commander",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-11/g/cf-lg-aff04d02-600b-4673-b5ca-f24770ad2be1.jpg",
      description:
        "Modern tool watch with topographic maps and tactical functions",
      msrp: "1950",
      review: "",
      releasedate: "10/2/2019",
      size: "Diameter x Thickness: 46 x 14.4 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "87 g (94 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[9]._id,
    },
    {
      name: "MARQ® Aviator",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-03/g/cf-lg-202f6cb2-08bc-401a-af69-d1f64f1dcab3.jpg",
      description:
        "Modern tool watch with 24-hour GMT bezel and Direct-to navigation",
      msrp: "1950",
      review: "",
      releasedate: "3/13/2019",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "144 g (95 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
    {
      name: "MARQ® Captain",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-06/g/cf-lg-30b544c6-25b4-4fda-a718-c32d16e10dea.jpg",
      description: "Modern tool watch with advanced nautical features",
      msrp: "1850",
      review: "",
      releasedate: "3/13/2019",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "88 g (95 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[15]._id,
    },
    {
      name: "MARQ® Adventurer",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-26/g/cf-lg-fe412f6d-0f17-49e1-811c-eaff50eb230b.jpg",
      description:
        "Modern tool watch with topographic maps and Pulse Ox acclimation sensor",
      msrp: "1750",
      review: "",
      releasedate: "3/13/2019",
      size: "Diameter x Thickness: 46 x 14.2 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "87 g (94 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[10]._id,
    },
    {
      name: "MARQ® Athlete",
      picture:
        "https://static.garmincdn.com/en/products/010-02006-15/g/cf-lg-120a8992-5b52-4728-a64e-40998f3548f4.jpg",
      description:
        "Modern tool watch with recovery time and VO2 max scales on the bezel",
      msrp: "1500",
      review:
        "https://www.dcrainmaker.com/2019/08/garmin-marq-athlete-in-depthreviewhtml",
      releasedate: "3/13/2019",
      size: "Diameter x Thickness: 46 x 14.1 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "94 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[6]._id,
    },
    {
      name: "MARQ® Golfer",
      picture:
        "https://static.garmincdn.com/en/products/010-02394-00/g/cf-lg-1b110fa8-21b0-4fdd-9237-2f2c99bddb11.jpg",
      description:
        "Modern tool watch with Virtual Caddie and thousands of preloaded courses worldwide",
      msrp: "1850",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm\n",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "88 g (95 g with silicone rubber)",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[12]._id,
    },
    {
      name: "MARQ® Driver Performance Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02567-00/g/cf-lg-c5f3d700-9d74-4394-8eb0-294291ad7707.jpg",
      description: "Modern tool watch with tachymeter and preloaded racetracks",
      msrp: "1680",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "95 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[16]._id,
    },
    {
      name: "MARQ® Captain: American Magic Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02454-00/g/cf-lg-dd0c1a30-e449-43b6-a076-b3ad59e3b72b.jpg",
      description: "Modern tool watch that champions the pursuit of greatness",
      msrp: "1400",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "95 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[6]._id,
    },
    {
      name: "MARQ® Athlete Performance Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02567-20/g/cf-lg-e5a85376-d962-45aa-9763-82e067bb5ab0.jpg",
      description:
        "Modern tool watch with recovery time and VO2 max scales on the bezel",
      msrp: "1360",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "94 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[6]._id,
    },
    {
      name: "MARQ® Adventurer Performance Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02567-30/g/cf-lg-dd2cff3b-8234-4487-abd8-ccd7fd147540.jpg",
      description:
        "Modern tool watch with topographic maps and Pulse Ox acclimation sensor",
      msrp: "1280",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "95 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[10]._id,
    },
    {
      name: "MARQ® Aviator Performance Edition",
      picture:
        "https://static.garmincdn.com/en/products/010-02567-10/g/cf-lg-30273226-d8fd-4982-bf3b-8c176be118d8.jpg",
      description:
        "Modern tool watch with 24-hour GMT bezel and Direct-to navigation",
      msrp: "1280",
      review: "",
      releasedate: "",
      size: "Diameter x Thickness: 46 x 14.7 mm",
      displaysize: "1.2” (30.4 mm) diameter",
      displayresolution: "240 x 240 pixels",
      weight: "95 g",
      waterrating: "10 ATM",
      colordisplay: "Yes",
      category: categories[13]._id,
    },
  ]);

  console.log("products seeded");

  process.exit();
});
